before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm64

archives:
- format_overrides:
  - goos: windows
    format: zip
  files:
  - none*
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
signs:
  - artifacts: checksum
    args: ["--batch", "-u", "D121C72DD3E53449", "--output", "${signature}", "--detach-sign", "${artifact}"]
